---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-jwt-secret
  namespace: mini-ecommerce
spec:
  encryptedData:
    INTERNAL_SERVICE_TOKEN: AgCKdsmhf8SIqTRQRWQiD3lOYSA+q6yUlRcjiSME2NRwynl3H7INpCZvLi3RdOv2oxRmUTYfEy9Rrm9hB6f37w0QGZrS5nGMgYmJSSJxqLffjaOMp8QKR2HkWOSIICUlop0eT8b8kM34AdRyyIUFsRgO9vjmR1B/F0PhgGoXDchGrb+6murg+ugvL/kl6FQYf8dDk5s10YETiCCCawHe/Nilx2eEBEwAmz/BTFW5m/Nm/fLqBK7TlmVstG4vHx++QcvgPzv5uek5XTz9tYYfjur70BSUj43cZxrKG4SUmXyR1Dw+ka3BhumN5nydir6Rj/DCzfSrJb3XcAU0JqvZ3HJJdJgS0z3qn8wBWpb7tqP7Cmeg1LHaGAJ/EEu0W/yZuLGowFojUForS2tiBNFQvApiEMR/QLbxRZyffPcjL8pQclc8+VftqXHjeXvv9BVtfCeDzWqQOECQZjPvgcpWBW7ZskHrDbz9OGKiIgnrMdLOOvNMn/GNMpu0q3Jb+ycSNq1PJN4xkzrYWGZL3VY7Rmd1kJa0kwcRWfEuYIBSJkfVLv4cRMObbVvtuks4lHwUlkapVcInJ0+jeH2UZpo4SaG1f5KZtYrxzxZ3lD2hypcH3HGUWB34OiWm7gUMg541owD1D66VFiAhNRQ54fDltCQcA2XDqn4db0RqJhK0KOvob564sIh1hC6W8g8DLg4V5TzaOGLHObJw9bo=
    JWT_SECRET: AgAaWjssh6eSPpDL50YpejdISs7zS/mW5UutcfiolfU2RvEzY6xiPVcDkHcTHBhASTHKKLFWwCCejTVtuinZHvZZTWSaNI2fvhsg+sBUiNdcJpHvlTH9R6+fqwKjNLBKXtsz9B2ouuWuas4hFiSmW6Kcl+oi1MrK9+PGiNmtUk2A+d22SpuxrIvnuBjFFrO12CpcOxBRsm+I/q4DHKrxA0EB/pPrB+C/A6bOc0YWVtJe6kXRhVkF9bb6e8jaX/t759KWyHk3zabQCDHSh89ZofFlRJlpMJO53j6hFEVMWfLUMmdwleI1fr6Bz+aZpYFv3XrEyF/cqaBXR6iy4NV6O+A3iR/A8zwDnclM4ScMjIl4/MBrBoPA8PhEGWXhyNOqZrTg9ta5WmNVu1wf78AyYNHeB6zsiifELM8RIMlfykD6hCAY5ejW3fR3l9PdfikhMRVKbNpt/ZyiaZ0OKAaCAkxQrtX/xyYNb5crD6v+A576CiEqS8z5MHqnsQfAwjzhVNzuqPiqqrka6K8uDAUQDtj/ck9nCA+8yDts8qADJvt+N0ENO9tD7cA1s7Po3i8KTyJkp0PN14lp3MSc6aRJLV+oIzJcKmTfQT6Vsr0XGJYr62LYdOsZaENYFp/UaeRiL/SuOkP5YrTsEn4ZJscso7divDmQ2LhgBRL1/YThaE/ADc5P3X7vVaP6tcf2FPERP/jlr6IKvikcvHE=
  template:
    metadata:
      name: auth-jwt-secret
      namespace: mini-ecommerce
    type: Opaque
