apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mini-ecommerce-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/NT114-Q21-Specialized-Project/kubernetes-hub.git
    targetRevision: main
    path: overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: mini-ecommerce

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
